apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: batch-job-container
          image: liquid8796/spring-batch-kubernates
          imagePullPolicy: IfNotPresent